//
//  XMLAPIErrorCode.m
//  EngageSDK
//
//  Created by Lindsay Thurmond on 1/27/15.
//  Copyright  = c) 2015 Silverpop. All rights reserved.
//

#import "XMLAPIErrorCode.h"

@implementation XMLAPIErrorCode

int const XMLAPI_ERROR_FTF_NON_NUMERIC_MAILING_KEY = 1;

int const XMLAPI_ERROR_FTF_NON_NUMERIC_SENDER_KEY = 2;

int const XMLAPI_ERROR_FTF_BAD_MAILING = 3;

int const XMLAPI_ERROR_FTF_INVALID_EMAIL_ADDRESS = 4;

int const XMLAPI_ERROR_FTF_INVALID_ENCRYPTED_SENDER_KEY = 5;

int const XMLAPI_ERROR_FTF_INVALID_COMMENT_SIZE = 6;

int const XMLAPI_ERROR_SERVER_ERROR = 50;

int const XMLAPI_ERROR_INVALID_XML_REQUEST = 51;

int const XMLAPI_ERROR_MISSING_XML_PARAMETER = 52;

int const XMLAPI_ERROR_PARAM_NOT_PROVIDED = 100;

int const XMLAPI_ERROR_NAME_ALREADY_IN_USE = 101;

int const XMLAPI_ERROR_DIRECTORY_ALREADY_EXISTS = 102;

int const XMLAPI_ERROR_PARENT_DIRECTORY_DOES_NOT_EXIST = 103;

int const XMLAPI_ERROR_VISIBILITY_NOT_VALID = 104;

int const XMLAPI_ERROR_LIST_TYPE_NOT_VALID = 105;

int const XMLAPI_ERROR_LIST_ID_NOT_VALID = 106;

int const XMLAPI_ERROR_MAILING_ID_NOT_VALID = 107;

int const XMLAPI_ERROR_TRACKING_LEVEL_NOT_VALID = 108;

int const XMLAPI_ERROR_ERROR_SAVING_MAILING = 109;

int const XMLAPI_ERROR_RETAIN_FLAG_NOT_VALID = 110;

int const XMLAPI_ERROR_MAILING_TYPE_NOT_VALID = 111;

int const XMLAPI_ERROR_CLICK_THROUGH_TYPE_NOT_VALID = 112;

int const XMLAPI_ERROR_TEXT_SIZE_NOT_INT = 113;

int const XMLAPI_ERROR_PARAM_NOT_PROVIDED_2 = 114;

int const XMLAPI_ERROR_NAME_ALREADY_IN_USE_2 = 115;

int const XMLAPI_ERROR_ERR_INVALID_CREATED_FROM = 116;

int const XMLAPI_ERROR_ERR_INVALID_ALLOW_HTML = 117;

int const XMLAPI_ERROR_ERR_INVALID_SEND_AUTOREPLY = 118;

int const XMLAPI_ERROR_ERR_INVALID_UPDATE_IF_FOUND = 119;

int const XMLAPI_ERROR_ERROR_SAVING_RECIPIENT = 120;

int const XMLAPI_ERROR_ADD_RECIPIENT_EMAIL_REQUIRED = 121;

int const XMLAPI_ERROR_ADD_RECIPIENT_ALREADY_EXISTS = 122;

int const XMLAPI_ERROR_UPDATE_RECIPIENT_DOES_NOT_EXIST = 123;

int const XMLAPI_ERROR_RECIPIENT_ID_NOT_VALID = 124;

int const XMLAPI_ERROR_LIST_ID_OR_MAILING_ID_REQUIRED = 125;

int const XMLAPI_ERROR_MAILING_DOES_NOT_EXIST = 126;

int const XMLAPI_ERROR_MAILING_DELETED = 127;

int const XMLAPI_ERROR_RECIPIENT_NOT_LIST_MEMBER = 128;

int const XMLAPI_ERROR_RECIPIENT_OPTED_OUT = 129;

int const XMLAPI_ERROR_MAILING_INTERNAL_ERROR = 130;

int const XMLAPI_ERROR_ERR_INVALID_IMPORT_TYPE = 131;

int const XMLAPI_ERROR_IMPORT_JOB_CREATE_ERROR = 132;

int const XMLAPI_ERROR_FILE_TYPE_NOT_VALID = 133;

int const XMLAPI_ERROR_FILE_TYPE_NOT_VALID_2 = 134;

int const XMLAPI_ERROR_JOB_ID_NOT_VALID = 135;

int const XMLAPI_ERROR_DELETE_JOB_INTERNAL_ERROR = 136;

int const XMLAPI_ERROR_DESTROY_MAILING_INTERNAL_ERROR = 137;

int const XMLAPI_ERROR_REMOVE_RECIPIENT_INTERNAL_ERROR = 138;

int const XMLAPI_ERROR_CANNOT_CREATE_DC_RULESET_EXPORT = 139;

int const XMLAPI_ERROR_EDITOR_TYPE_NOT_VALID = 140;

int const XMLAPI_ERROR_ENCODING_NOT_VALID = 141;

int const XMLAPI_ERROR_CANNOT_DELETE_LIST_QUERY_RECIPIENTS = 143;

int const XMLAPI_ERROR_INVALID_SESSION = 145;

int const XMLAPI_ERROR_INVALID_LIST_COLUMN_TYPE = 146;

int const XMLAPI_ERROR_INCLUDE_ALL_LISTS_NOT_VALID = 147;

int const XMLAPI_ERROR_INVALID_PERMISSIONS = 150;

int const XMLAPI_ERROR_ERR_LIST_META_DENIED = 151;

int const XMLAPI_ERROR_CREATE_COLUMNS_INTERNAL_ERROR = 152;

int const XMLAPI_ERROR_ERR_EXPORT_NOT_LIST_COLUMN = 153;

int const XMLAPI_ERROR_ACTION_CODE_NOT_VALID = 154;

int const XMLAPI_ERROR_RULESET_DOES_NOT_EXIST = 155;

int const XMLAPI_ERROR_CREATE_EXPORT_JOB_INTERNAL_ERROR = 156;

int const XMLAPI_ERROR_CUSTOM_MAILING_ID_REQUIRED = 160;

int const XMLAPI_ERROR_COLUMN_NAME_NOT_VALID = 161;

int const XMLAPI_ERROR_MAILING_NOT_ACTIVE = 162;

int const XMLAPI_ERROR_DELETE_RULESET_SQL_ERROR = 170;

int const XMLAPI_ERROR_DELETE_RULESET_ERROR = 171;

int const XMLAPI_ERROR_USAGE_NOT_INTEGER = 172;

int const XMLAPI_ERROR_DYNAMIC_CONTENT_RULESET_SQL_ERROR = 173;

int const XMLAPI_ERROR_DYNAMIC_CONTENT_RULESET_SQL_ERROR_2 = 174;

int const XMLAPI_ERROR_USER_EXISTS_INTERNAL_ERROR = 180;

int const XMLAPI_ERROR_CANNOT_SCHEDULE_MULTIMATCH_MAILINGS = 181;

int const XMLAPI_ERROR_MAILING_NAME_ALREADY_EXISTS = 182;

int const XMLAPI_ERROR_MAILING_VALIDATION_ERROR = 183;

int const XMLAPI_ERROR_DATE_ERROR = 184;

int const XMLAPI_ERROR_BEHAVIOR_REPORT_ID_NOT_VALID = 185;

int const XMLAPI_ERROR_ERR_INVALID_SENT_MAILING_TYPE = 186;

int const XMLAPI_ERROR_RECURSIVE_NOT_VALID = 187;

int const XMLAPI_ERROR_LIST_COLUMN_CANNOT_BE_SYSTEM_FIELD = 188;

int const XMLAPI_ERROR_CANNOT_LOCATE_ELEMENT = 190;

int const XMLAPI_ERROR_CREATE_QUERY_NAME_ALREADY_EXISTS = 256;

int const XMLAPI_ERROR_RULESET_WITH_NAME_ALREADY_EXISTS = 300;

int const XMLAPI_ERROR_RULESET_WITH_NAME_DOES_NOT_EXIST = 301;

int const XMLAPI_ERROR_LIST_ID_NOT_INTEGER = 310;

int const XMLAPI_ERROR_CREATE_RECIPIENT_DATA_JOB_INTERNAL_ERROR = 311;

int const XMLAPI_ERROR_LIST_TYPE_NOT_VALID_2 = 312;

int const XMLAPI_ERROR_COLUMN_TYPE_NOT_VALID = 313;

int const XMLAPI_ERROR_COLUMN_NOT_FOUND = 314;

int const XMLAPI_ERROR_RECIPIENT_OPT_OUT_INTERNAL_ERROR = 315;

int const XMLAPI_ERROR_COLUMN_NAME_REQUIRED = 316;

int const XMLAPI_ERROR_MAILING_ID_AND_LIST_ID_SET = 320;

int const XMLAPI_ERROR_EXPORT_FORMAT_NOT_VALID = 321;

int const XMLAPI_ERROR_MAILING_CONTENT_ARCHIVED = 322;

int const XMLAPI_ERROR_FOLDER_ID_NOT_NUMBER = 323;

int const XMLAPI_ERROR_PARENT_FOLDER_VISIBILITY_MISMATCH = 314;

int const XMLAPI_ERROR_FOLDER_ID_NOT_FOUND = 325;

int const XMLAPI_ERROR_CANNOT_UPDATE_EMAIL = 326;

int const XMLAPI_ERROR_SYNC_FIELD_NAME_REQUIRED = 329;

int const XMLAPI_ERROR_MAILING_REPORT_DATA_NOT_AVAILABLE = 500;

int const XMLAPI_ERROR_QUERY_SAVE_ERROR = 600;

int const XMLAPI_ERROR_AUTO_RESPONDER_NOT_ACTIVE = 806;

int const XMLAPI_ERROR_RECIPIENT_ID_NOT_FOUND = 1001;

int const XMLAPI_ERROR_SYNC_ID_NOT_FOUND = 1002;

int const XMLAPI_ERROR_RECIPIENT_SAVE_ERROR = 1003;

int const XMLAPI_ERROR_RECIPIENT_RETRIEVE_ERROR = 1004;

int const XMLAPI_ERROR_RECIPIENT_ADD_ERROR = 1005;

int const XMLAPI_ERROR_RECIPIENT_KEY_MISSING = 1006;

int const XMLAPI_ERROR_COLUMN_DOES_NOT_EXIST = 1007;

int const XMLAPI_ERROR_RECIPIENT_NOT_FOUND = 1008;

int const XMLAPI_ERROR_RECIPIENT_ALREADY_DELETED = 1009;

int const XMLAPI_ERROR_CANNOT_UPDATE_SYSTEM_COLUMN = 1011;

int const XMLAPI_ERROR_RECIPIENT_MERGE_ERROR = 1015;

int const XMLAPI_ERROR_REQUIRED_COLUMN_VALUE = 1016;

int const XMLAPI_ERROR_EMAIL_NOT_VALID = 1017;

int const XMLAPI_ERROR_CONTACT_ALREADY_EXISTS = 1018;

@end